//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.04 at 04:49:42 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.codechallange.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.codechallangesoap.soapservice.soap;
