
package com.codechallangesoap.soapservice.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ClientesPortService", targetNamespace = "http://www.codechallange.com/", wsdlLocation = "http://localhost:8085/ws/clientes.wsdl")
public class ClientesPortService
    extends Service
{

    private static final URL CLIENTESPORTSERVICE_WSDL_LOCATION;
    private static final WebServiceException CLIENTESPORTSERVICE_EXCEPTION;
    private static final QName CLIENTESPORTSERVICE_QNAME = new QName("http://www.codechallange.com/", "ClientesPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/ws/clientes.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTESPORTSERVICE_WSDL_LOCATION = url;
        CLIENTESPORTSERVICE_EXCEPTION = e;
    }

    public ClientesPortService() {
        super(__getWsdlLocation(), CLIENTESPORTSERVICE_QNAME);
    }

    public ClientesPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTESPORTSERVICE_QNAME, features);
    }

    public ClientesPortService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTESPORTSERVICE_QNAME);
    }

    public ClientesPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTESPORTSERVICE_QNAME, features);
    }

    public ClientesPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientesPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientesPort
     */
    @WebEndpoint(name = "ClientesPortSoap11")
    public ClientesPort getClientesPortSoap11() {
        return super.getPort(new QName("http://www.codechallange.com/", "ClientesPortSoap11"), ClientesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientesPort
     */
    @WebEndpoint(name = "ClientesPortSoap11")
    public ClientesPort getClientesPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.codechallange.com/", "ClientesPortSoap11"), ClientesPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTESPORTSERVICE_EXCEPTION!= null) {
            throw CLIENTESPORTSERVICE_EXCEPTION;
        }
        return CLIENTESPORTSERVICE_WSDL_LOCATION;
    }

}
