
package com.codechallangesoap.soapservice.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ClientesPort", targetNamespace = "http://www.codechallange.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientesPort {


    /**
     * 
     * @param guardarCuentaRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.GuardarCuentaResponse
     */
    @WebMethod
    @WebResult(name = "guardarCuentaResponse", targetNamespace = "http://www.codechallange.com/", partName = "guardarCuentaResponse")
    public GuardarCuentaResponse guardarCuenta(
        @WebParam(name = "guardarCuentaRequest", targetNamespace = "http://www.codechallange.com/", partName = "guardarCuentaRequest")
        GuardarCuentaRequest guardarCuentaRequest);

    /**
     * 
     * @param eliminarCuentaRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.EliminarCuentaResponse
     */
    @WebMethod
    @WebResult(name = "eliminarCuentaResponse", targetNamespace = "http://www.codechallange.com/", partName = "eliminarCuentaResponse")
    public EliminarCuentaResponse eliminarCuenta(
        @WebParam(name = "eliminarCuentaRequest", targetNamespace = "http://www.codechallange.com/", partName = "eliminarCuentaRequest")
        EliminarCuentaRequest eliminarCuentaRequest);

    /**
     * 
     * @param guardarMovimientoRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.GuardarMovimientoResponse
     */
    @WebMethod
    @WebResult(name = "guardarMovimientoResponse", targetNamespace = "http://www.codechallange.com/", partName = "guardarMovimientoResponse")
    public GuardarMovimientoResponse guardarMovimiento(
        @WebParam(name = "guardarMovimientoRequest", targetNamespace = "http://www.codechallange.com/", partName = "guardarMovimientoRequest")
        GuardarMovimientoRequest guardarMovimientoRequest);

    /**
     * 
     * @param guardarClienteRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.GuardarClienteResponse
     */
    @WebMethod
    @WebResult(name = "guardarClienteResponse", targetNamespace = "http://www.codechallange.com/", partName = "guardarClienteResponse")
    public GuardarClienteResponse guardarCliente(
        @WebParam(name = "guardarClienteRequest", targetNamespace = "http://www.codechallange.com/", partName = "guardarClienteRequest")
        GuardarClienteRequest guardarClienteRequest);

    /**
     * 
     * @param actualizarClienteRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.ActualizarClienteResponse
     */
    @WebMethod
    @WebResult(name = "actualizarClienteResponse", targetNamespace = "http://www.codechallange.com/", partName = "actualizarClienteResponse")
    public ActualizarClienteResponse actualizarCliente(
        @WebParam(name = "actualizarClienteRequest", targetNamespace = "http://www.codechallange.com/", partName = "actualizarClienteRequest")
        ActualizarClienteRequest actualizarClienteRequest);

    /**
     * 
     * @param actualizarCuentaRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.ActualizarCuentaResponse
     */
    @WebMethod
    @WebResult(name = "actualizarCuentaResponse", targetNamespace = "http://www.codechallange.com/", partName = "actualizarCuentaResponse")
    public ActualizarCuentaResponse actualizarCuenta(
        @WebParam(name = "actualizarCuentaRequest", targetNamespace = "http://www.codechallange.com/", partName = "actualizarCuentaRequest")
        ActualizarCuentaRequest actualizarCuentaRequest);

    /**
     * 
     * @param eliminarClienteRequest
     * @return
     *     returns com.codechallangesoap.soapservice.soap.EliminarClienteResponse
     */
    @WebMethod
    @WebResult(name = "eliminarClienteResponse", targetNamespace = "http://www.codechallange.com/", partName = "eliminarClienteResponse")
    public EliminarClienteResponse eliminarCliente(
        @WebParam(name = "eliminarClienteRequest", targetNamespace = "http://www.codechallange.com/", partName = "eliminarClienteRequest")
        EliminarClienteRequest eliminarClienteRequest);

}
